-- Partner dashboard premium SaaS upgrade:
-- CMS labels for KPI cards, AI demand intelligence, one-click actions,
-- and future time planning.

insert into public.site_content (key, value_en, value_es, content_type, group_name)
values
  ('partner_greeting_template', 'Good afternoon, {{restaurant_name}}.', 'Buenas tardes, {{restaurant_name}}.', 'text', 'partner_dashboard'),
  ('partner_dashboard_kicker', 'Partner dashboard', 'Panel de partner', 'text', 'partner_dashboard'),
  ('partner_dashboard_intro', 'Your SmartTable operating cockpit for demand, offers, bookings, and AI recommendations.', 'Tu centro operativo de SmartTable para demanda, ofertas, reservas y recomendaciones de IA.', 'textarea', 'partner_dashboard'),
  ('partner_return_admin', 'Return to Super Admin', 'Volver a Super Admin', 'text', 'partner_dashboard'),
  ('partner_refresh', 'Refresh', 'Actualizar', 'text', 'partner_dashboard'),
  ('partner_today_kicker', 'Operations', 'Operaciones', 'text', 'partner_dashboard'),
  ('partner_today_overview_title', 'Today overview', 'Resumen de hoy', 'text', 'partner_dashboard'),
  ('partner_ai_actions_kicker', 'Automation', 'Automatizacion', 'text', 'partner_dashboard'),
  ('partner_ai_actions_title', 'One-click AI actions', 'Acciones de IA en un clic', 'text', 'partner_dashboard'),
  ('partner_apply_recommendation', 'Apply recommendation', 'Aplicar recomendacion', 'text', 'partner_dashboard'),
  ('partner_create_suggested_offer', 'Create suggested offer', 'Crear oferta sugerida', 'text', 'partner_dashboard'),
  ('partner_pause_low_offer', 'Pause low-performing offer', 'Pausar oferta de bajo rendimiento', 'text', 'partner_dashboard'),
  ('partner_current_recommendation', 'Current recommendation', 'Recomendacion actual', 'text', 'partner_dashboard'),
  ('partner_ai_recommendation_label', 'AI recommendation', 'Recomendacion de IA', 'text', 'partner_dashboard'),
  ('partner_ai_recommendation_fallback', 'Create a focused offer for the next lower-demand window and monitor conversion.', 'Crea una oferta enfocada para la proxima ventana de menor demanda y monitorea la conversion.', 'textarea', 'partner_dashboard'),
  ('partner_future_time_planning_kicker', 'Planning intelligence', 'Inteligencia de planificacion', 'text', 'partner_dashboard'),
  ('partner_future_time_planning_title', 'Future Time Planning', 'Planificacion futura del tiempo', 'text', 'partner_dashboard'),
  ('partner_future_time_planning_alert', 'Rain expected around 6 PM. Demand may drop by 18%. Recommend 20% discount between 5:30 PM and 7:00 PM.', 'Se espera lluvia alrededor de las 6 PM. La demanda puede bajar 18%. Recomendamos 20% de descuento entre 5:30 PM y 7:00 PM.', 'textarea', 'partner_dashboard'),
  ('partner_kpi_views', 'Views', 'Vistas', 'text', 'partner_dashboard'),
  ('partner_kpi_bookings', 'Bookings', 'Reservas', 'text', 'partner_dashboard'),
  ('partner_kpi_accepted', 'Accepted', 'Aceptadas', 'text', 'partner_dashboard'),
  ('partner_kpi_rejected', 'Rejected', 'Rechazadas', 'text', 'partner_dashboard'),
  ('partner_kpi_favorites', 'Favorites', 'Favoritos', 'text', 'partner_dashboard'),
  ('partner_kpi_favorites_week', 'Favorites this week', 'Favoritos esta semana', 'text', 'partner_dashboard'),
  ('partner_kpi_favorites_month', 'Favorites this month', 'Favoritos este mes', 'text', 'partner_dashboard'),
  ('partner_kpi_conversion', 'Conversion rate', 'Tasa de conversion', 'text', 'partner_dashboard'),
  ('partner_kpi_revenue_recovered', 'Revenue recovered', 'Ingresos recuperados', 'text', 'partner_dashboard'),
  ('partner_kpi_active_offers', 'Active offers', 'Ofertas activas', 'text', 'partner_dashboard'),
  ('partner_todays_bookings', 'Today''s bookings', 'Reservas de hoy', 'text', 'partner_dashboard'),
  ('partner_expected_guests', 'Expected guests', 'Clientes esperados', 'text', 'partner_dashboard'),
  ('partner_today_active_offers', 'Active offers', 'Ofertas activas', 'text', 'partner_dashboard'),
  ('partner_demand_score', 'Demand score', 'Puntaje de demanda', 'text', 'partner_dashboard'),
  ('partner_suggested_discount', 'Suggested discount', 'Descuento sugerido', 'text', 'partner_dashboard'),
  ('partner_trend_label', 'Trend', 'Tendencia', 'text', 'partner_dashboard'),
  ('partner_confidence_label', 'Confidence', 'Confianza', 'text', 'partner_dashboard'),
  ('partner_expected_bookings', 'Expected bookings', 'Reservas esperadas', 'text', 'partner_dashboard'),
  ('partner_expected_revenue_lift', 'Expected revenue lift', 'Aumento esperado de ingresos', 'text', 'partner_dashboard'),
  ('partner_suggested_action', 'Suggested action', 'Accion sugerida', 'text', 'partner_dashboard'),
  ('partner_revenue_without_discount', 'Without suggested discount', 'Sin descuento sugerido', 'text', 'partner_dashboard'),
  ('partner_revenue_with_discount', 'With suggested discount', 'Con descuento sugerido', 'text', 'partner_dashboard'),
  ('partner_revenue_lift', 'Lift', 'Incremento', 'text', 'partner_dashboard'),
  ('partner_reservations_signal', 'reservations signal', 'senal de reservas', 'text', 'partner_dashboard'),
  ('partner_active_offers_signal', 'active offers', 'ofertas activas', 'text', 'partner_dashboard'),
  ('partner_views_signal', 'views', 'vistas', 'text', 'partner_dashboard'),
  ('partner_planning_weather', 'Weather', 'Clima', 'text', 'partner_dashboard'),
  ('partner_planning_traffic', 'Traffic', 'Trafico', 'text', 'partner_dashboard'),
  ('partner_planning_parking', 'Parking', 'Estacionamiento', 'text', 'partner_dashboard'),
  ('partner_planning_walking_time', 'Walking time', 'Tiempo caminando', 'text', 'partner_dashboard'),
  ('partner_planning_transit', 'Transit', 'Transporte publico', 'text', 'partner_dashboard'),
  ('partner_planning_nearby_events', 'Nearby events', 'Eventos cercanos', 'text', 'partner_dashboard'),
  ('partner_planning_service_duration', 'Service duration', 'Duracion del servicio', 'text', 'partner_dashboard'),
  ('partner_planning_best_booking_windows', 'Best booking windows', 'Mejores ventanas de reserva', 'text', 'partner_dashboard'),
  ('partner_planning_risk_alerts', 'Risk alerts', 'Alertas de riesgo', 'text', 'partner_dashboard'),
  ('partner_planning_status_good', 'good', 'bien', 'text', 'partner_dashboard'),
  ('partner_planning_status_watch', 'watch', 'vigilar', 'text', 'partner_dashboard'),
  ('partner_planning_status_risk', 'risk', 'riesgo', 'text', 'partner_dashboard'),
  ('partner_nav_overview', 'Overview', 'Resumen', 'text', 'partner_dashboard'),
  ('partner_nav_today', 'Today', 'Hoy', 'text', 'partner_dashboard'),
  ('partner_nav_ai_actions', 'AI actions', 'Acciones IA', 'text', 'partner_dashboard'),
  ('partner_nav_ai_demand', 'AI demand', 'Demanda IA', 'text', 'partner_dashboard'),
  ('partner_nav_time_planning', 'Time planning', 'Planificacion', 'text', 'partner_dashboard'),
  ('partner_nav_intelligence', 'Intelligence', 'Inteligencia', 'text', 'partner_dashboard'),
  ('partner_nav_profile', 'Profile', 'Perfil', 'text', 'partner_dashboard'),
  ('partner_nav_create_offer', 'Create offer', 'Crear oferta', 'text', 'partner_dashboard'),
  ('partner_nav_offers', 'Offers', 'Ofertas', 'text', 'partner_dashboard'),
  ('partner_nav_reservations', 'Reservations', 'Reservas', 'text', 'partner_dashboard')
on conflict (key) do update set
  value_en = excluded.value_en,
  value_es = excluded.value_es,
  content_type = excluded.content_type,
  group_name = excluded.group_name,
  updated_at = now();
