-- Partner AI Revenue Operating System dashboard content keys.

insert into public.site_content (key, value_en, value_es, content_type, group_name)
values
  ('partner_generic_name', 'Partner', 'Socio', 'text', 'partner_dashboard'),
  ('partner_nav_executive', 'Executive', 'Ejecutivo', 'text', 'partner_dashboard'),
  ('partner_nav_opportunity', 'Opportunity', 'Oportunidad', 'text', 'partner_dashboard'),
  ('partner_nav_risk', 'Risk', 'Riesgo', 'text', 'partner_dashboard'),
  ('partner_nav_health', 'Health', 'Salud', 'text', 'partner_dashboard'),
  ('partner_nav_market', 'Market', 'Mercado', 'text', 'partner_dashboard'),
  ('partner_nav_timeline', 'Timeline', 'Linea de tiempo', 'text', 'partner_dashboard'),
  ('partner_nav_confidence', 'Confidence', 'Confianza', 'text', 'partner_dashboard'),
  ('partner_nav_roi', 'ROI', 'ROI', 'text', 'partner_dashboard'),
  ('executive_kicker', 'AI Revenue Operating System', 'Sistema operativo de ingresos con IA', 'text', 'partner_dashboard'),
  ('executive_title', 'Good morning, {{restaurant_name}}!', 'Buenos dias, {{restaurant_name}}!', 'text', 'partner_dashboard'),
  ('executive_subtitle', 'Your AI Revenue Manager has analyzed today''s demand, guest behavior, weather, traffic, and booking signals.', 'Tu gerente de ingresos IA analizo la demanda de hoy, comportamiento de clientes, clima, trafico y senales de reservas.', 'textarea', 'partner_dashboard'),
  ('executive_message', 'Yesterday you may have missed approximately {{missed_revenue}} because Friday lunch demand stayed below normal. Today SmartTable can help recover an estimated {{recoverable_revenue}} with the recommended actions below.', 'Ayer podrias haber perdido aproximadamente {{missed_revenue}} porque la demanda de almuerzo del viernes estuvo por debajo de lo normal. Hoy SmartTable puede ayudar a recuperar un estimado de {{recoverable_revenue}} con las acciones recomendadas.', 'textarea', 'partner_dashboard'),
  ('executive_action_lunch_offer', 'Create 15% Lunch Offer', 'Crear oferta de almuerzo 15%', 'text', 'partner_dashboard'),
  ('executive_action_notify_favorites', 'Notify favorite guests', 'Notificar clientes favoritos', 'text', 'partner_dashboard'),
  ('executive_action_increase_dinner', 'Increase early dinner availability', 'Aumentar disponibilidad de cena temprana', 'text', 'partner_dashboard'),
  ('executive_apply_all', 'Apply all recommendations', 'Aplicar todas las recomendaciones', 'text', 'partner_dashboard'),
  ('executive_apply_all_success', 'All AI recommendations applied.', 'Todas las recomendaciones IA fueron aplicadas.', 'text', 'partner_dashboard'),
  ('daily_opportunity_kicker', 'Daily Revenue Opportunity', 'Oportunidad diaria de ingresos', 'text', 'partner_dashboard'),
  ('daily_opportunity_title', 'You can earn +{{amount}} today', 'Puedes ganar +{{amount}} hoy', 'text', 'partner_dashboard'),
  ('daily_opportunity_percent', 'Revenue opportunity', 'Oportunidad de ingresos', 'text', 'partner_dashboard'),
  ('risk_kicker', 'Revenue protection', 'Proteccion de ingresos', 'text', 'partner_dashboard'),
  ('risk_title', 'Today''s Risk Signals', 'Senales de riesgo de hoy', 'text', 'partner_dashboard'),
  ('risk_tonight_demand', 'Tonight demand risk', 'Riesgo de demanda esta noche', 'text', 'partner_dashboard'),
  ('risk_saturday_sold_out', 'Saturday sold-out probability', 'Probabilidad de lleno el sabado', 'text', 'partner_dashboard'),
  ('risk_rain_impact', 'Rain impact', 'Impacto de lluvia', 'text', 'partner_dashboard'),
  ('risk_traffic', 'Traffic risk', 'Riesgo de trafico', 'text', 'partner_dashboard'),
  ('risk_parking', 'Parking risk', 'Riesgo de estacionamiento', 'text', 'partner_dashboard'),
  ('risk_late_dinner', 'Late dinner weakness', 'Debilidad en cena tarde', 'text', 'partner_dashboard'),
  ('risk_medium', 'Medium', 'Medio', 'text', 'partner_dashboard'),
  ('risk_high', 'High', 'Alto', 'text', 'partner_dashboard'),
  ('recommendation_why_title', 'Why this recommendation?', 'Por que esta recomendacion?', 'text', 'partner_dashboard'),
  ('recommendation_why_intro', 'We recommend this because:', 'Recomendamos esto porque:', 'text', 'partner_dashboard'),
  ('why_rain_after_8', 'Rain starts after 8 PM', 'La lluvia empieza despues de las 8 PM', 'text', 'partner_dashboard'),
  ('why_conversion_improves', 'Historical conversion improves by 31%', 'La conversion historica mejora 31%', 'text', 'partner_dashboard'),
  ('why_nearby_event', 'Nearby event may increase early dinner traffic', 'Un evento cercano puede aumentar el trafico de cena temprana', 'text', 'partner_dashboard'),
  ('why_parking_normal', 'Parking availability is normal', 'La disponibilidad de estacionamiento es normal', 'text', 'partner_dashboard'),
  ('why_late_dinner_weak', 'Late dinner demand is weak', 'La demanda de cena tarde es debil', 'text', 'partner_dashboard'),
  ('why_favorites_intent', 'Guests who favorited you have higher conversion intent', 'Los clientes que te marcaron como favorito tienen mayor intencion de reservar', 'text', 'partner_dashboard'),
  ('why_warm_audience', 'New offers perform better when sent to warm audiences', 'Las nuevas ofertas funcionan mejor con audiencias interesadas', 'text', 'partner_dashboard'),
  ('why_no_personal_shared', 'No personal behavior is shared with the restaurant', 'No se comparte comportamiento personal con el restaurante', 'text', 'partner_dashboard'),
  ('why_notifications_recover', 'Notifications can recover quiet-table demand', 'Las notificaciones pueden recuperar demanda en mesas tranquilas', 'text', 'partner_dashboard'),
  ('why_late_weaker', 'Late dinner demand is weaker than early dinner', 'La demanda de cena tarde es mas debil que la cena temprana', 'text', 'partner_dashboard'),
  ('why_flexible_value', 'Flexible guests respond to sharper last-minute value', 'Los clientes flexibles responden a mejor valor de ultimo minuto', 'text', 'partner_dashboard'),
  ('why_traffic_drops', 'Traffic pressure drops later in the evening', 'La presion de trafico baja mas tarde en la noche', 'text', 'partner_dashboard'),
  ('why_guardrails', 'Discounts stay inside restaurant-defined guardrails', 'Los descuentos permanecen dentro de reglas definidas por el restaurante', 'text', 'partner_dashboard'),
  ('why_high_demand_no_max', 'High-demand windows do not need maximum incentives', 'Las ventanas de alta demanda no necesitan incentivos maximos', 'text', 'partner_dashboard'),
  ('why_lower_first', 'Guests can convert at a lower discount first', 'Los clientes pueden convertir primero con un descuento menor', 'text', 'partner_dashboard'),
  ('why_margin_priority', 'SmartTable prioritizes restaurant margin when demand rises', 'SmartTable prioriza el margen del restaurante cuando sube la demanda', 'text', 'partner_dashboard'),
  ('why_increase_later', 'Discounts can be increased later if conversion slows', 'Los descuentos pueden subir despues si baja la conversion', 'text', 'partner_dashboard'),
  ('health_kicker', 'Restaurant Health Score', 'Puntaje de salud del restaurante', 'text', 'partner_dashboard'),
  ('health_title', 'Restaurant Health Score', 'Puntaje de salud del restaurante', 'text', 'partner_dashboard'),
  ('health_overall', 'Overall Health', 'Salud general', 'text', 'partner_dashboard'),
  ('health_revenue', 'Revenue', 'Ingresos', 'text', 'partner_dashboard'),
  ('health_guest_demand', 'Guest Demand', 'Demanda de clientes', 'text', 'partner_dashboard'),
  ('health_reputation', 'Reputation', 'Reputacion', 'text', 'partner_dashboard'),
  ('health_operations', 'Operations', 'Operaciones', 'text', 'partner_dashboard'),
  ('health_ai_efficiency', 'AI Efficiency', 'Eficiencia IA', 'text', 'partner_dashboard'),
  ('market_kicker', 'Live Market Signals', 'Senales de mercado en vivo', 'text', 'partner_dashboard'),
  ('market_title', 'Live Market Signals', 'Senales de mercado en vivo', 'text', 'partner_dashboard'),
  ('market_map_placeholder', 'Neighborhood signal map', 'Mapa de senales del vecindario', 'text', 'partner_dashboard'),
  ('market_map_note', 'Google Maps and live provider layers are prepared for future integration.', 'Google Maps y capas de proveedores en vivo estan preparados para integracion futura.', 'textarea', 'partner_dashboard'),
  ('market_nearby_events', 'Nearby events', 'Eventos cercanos', 'text', 'partner_dashboard'),
  ('market_hotels', 'Hotels', 'Hoteles', 'text', 'partner_dashboard'),
  ('market_offices', 'Offices', 'Oficinas', 'text', 'partner_dashboard'),
  ('market_traffic', 'Traffic', 'Trafico', 'text', 'partner_dashboard'),
  ('market_subway', 'Subway access', 'Acceso al metro', 'text', 'partner_dashboard'),
  ('market_parking', 'Parking', 'Estacionamiento', 'text', 'partner_dashboard'),
  ('market_competitors', 'Competitors', 'Competidores', 'text', 'partner_dashboard'),
  ('market_weather', 'Weather', 'Clima', 'text', 'partner_dashboard'),
  ('timeline_kicker', 'AI Forecast Timeline', 'Linea de pronostico IA', 'text', 'partner_dashboard'),
  ('timeline_title', 'Today''s Demand Forecast', 'Pronostico de demanda de hoy', 'text', 'partner_dashboard'),
  ('timeline_rising', 'Demand rising', 'Demanda subiendo', 'text', 'partner_dashboard'),
  ('timeline_normal', 'Normal', 'Normal', 'text', 'partner_dashboard'),
  ('timeline_weak', 'Weak', 'Debil', 'text', 'partner_dashboard'),
  ('timeline_high', 'High', 'Alta', 'text', 'partner_dashboard'),
  ('timeline_peak', 'Peak', 'Pico', 'text', 'partner_dashboard'),
  ('timeline_drop', 'Drop', 'Baja', 'text', 'partner_dashboard'),
  ('learning_kicker', 'AI Learning', 'Aprendizaje IA', 'text', 'partner_dashboard'),
  ('learning_title', 'SmartTable AI has analyzed', 'La IA de SmartTable ha analizado', 'text', 'partner_dashboard'),
  ('learning_confidence', 'AI confidence today', 'Confianza IA hoy', 'text', 'partner_dashboard'),
  ('learning_weather', 'Weather patterns', 'Patrones climaticos', 'text', 'partner_dashboard'),
  ('learning_traffic', 'Traffic signals', 'Senales de trafico', 'text', 'partner_dashboard'),
  ('learning_seasonality', 'Seasonality', 'Estacionalidad', 'text', 'partner_dashboard'),
  ('learning_holidays', 'Holiday trends', 'Tendencias de festivos', 'text', 'partner_dashboard'),
  ('learning_competitors', 'Competitor signals', 'Senales de competidores', 'text', 'partner_dashboard'),
  ('learning_events', 'Local events', 'Eventos locales', 'text', 'partner_dashboard'),
  ('roi_kicker', 'SmartTable ROI', 'ROI de SmartTable', 'text', 'partner_dashboard'),
  ('roi_title', 'SmartTable ROI', 'ROI de SmartTable', 'text', 'partner_dashboard'),
  ('roi_without', 'Without SmartTable', 'Sin SmartTable', 'text', 'partner_dashboard'),
  ('roi_with', 'With SmartTable', 'Con SmartTable', 'text', 'partner_dashboard'),
  ('roi_recovered', 'Recovered revenue', 'Ingresos recuperados', 'text', 'partner_dashboard'),
  ('roi_lift', 'ROI lift', 'Incremento ROI', 'text', 'partner_dashboard')
on conflict (key) do update set
  value_en = excluded.value_en,
  value_es = excluded.value_es,
  content_type = excluded.content_type,
  group_name = excluded.group_name,
  updated_at = now();
