-- Partner portfolio, operations intelligence, one-click AI actions,
-- pricing, staffing, VIP, and marketing generator content.

insert into public.site_content (key, value_en, value_es, content_type, group_name)
values
  ('partner_nav_portfolio', 'Portfolio', 'Portafolio', 'text', 'partner_dashboard'),
  ('partner_nav_pricing', 'Pricing', 'Precios', 'text', 'partner_dashboard'),
  ('partner_nav_staff', 'Staff', 'Personal', 'text', 'partner_dashboard'),
  ('partner_nav_events', 'Events', 'Eventos', 'text', 'partner_dashboard'),
  ('partner_nav_ltv', 'LTV', 'LTV', 'text', 'partner_dashboard'),
  ('partner_nav_vip', 'VIP', 'VIP', 'text', 'partner_dashboard'),
  ('partner_nav_marketing', 'Marketing', 'Marketing', 'text', 'partner_dashboard'),
  ('portfolio_kicker', 'Multi-restaurant intelligence', 'Inteligencia multi-restaurante', 'text', 'partner_dashboard'),
  ('portfolio_title', 'Portfolio View', 'Vista de portafolio', 'text', 'partner_dashboard'),
  ('portfolio_filter_all', 'All', 'Todos', 'text', 'partner_dashboard'),
  ('portfolio_filter_strong', 'Strong', 'Fuerte', 'text', 'partner_dashboard'),
  ('portfolio_filter_needs_action', 'Needs action', 'Necesita accion', 'text', 'partner_dashboard'),
  ('portfolio_filter_risk', 'Risk', 'Riesgo', 'text', 'partner_dashboard'),
  ('portfolio_health_label', 'Health', 'Salud', 'text', 'partner_dashboard'),
  ('portfolio_note', 'Demo portfolio structure for future franchise and multi-location owners.', 'Estructura demo de portafolio para futuros duenos de franquicias y multiples ubicaciones.', 'textarea', 'partner_dashboard'),
  ('action_generate_marketing', 'Generate marketing message', 'Generar mensaje de marketing', 'text', 'partner_dashboard'),
  ('action_create_social', 'Create social post', 'Crear publicacion social', 'text', 'partner_dashboard'),
  ('action_send_email_campaign', 'Send email campaign', 'Enviar campana de email', 'text', 'partner_dashboard'),
  ('action_optimize_pricing', 'Optimize today''s pricing', 'Optimizar precios de hoy', 'text', 'partner_dashboard'),
  ('ai_action_success', 'AI action applied successfully.', 'Accion de IA aplicada correctamente.', 'text', 'partner_dashboard'),
  ('pricing_kicker', 'AI Pricing Engine', 'Motor de precios IA', 'text', 'partner_dashboard'),
  ('pricing_title', 'AI Pricing Engine', 'Motor de precios IA', 'text', 'partner_dashboard'),
  ('pricing_apply', 'Apply AI pricing', 'Aplicar precios IA', 'text', 'partner_dashboard'),
  ('pricing_current_discount', 'Current discount', 'Descuento actual', 'text', 'partner_dashboard'),
  ('pricing_recommended_discount', 'Recommended discount', 'Descuento recomendado', 'text', 'partner_dashboard'),
  ('pricing_margin_protection', 'Margin protection', 'Proteccion de margen', 'text', 'partner_dashboard'),
  ('pricing_margin_active', 'Active', 'Activo', 'text', 'partner_dashboard'),
  ('pricing_conversion_lift', 'Expected conversion lift', 'Incremento esperado de conversion', 'text', 'partner_dashboard'),
  ('pricing_revenue_impact', 'Expected revenue impact', 'Impacto esperado en ingresos', 'text', 'partner_dashboard'),
  ('pricing_applied_notice', 'AI pricing optimization applied.', 'Optimizacion de precios IA aplicada.', 'text', 'partner_dashboard'),
  ('staff_kicker', 'AI Staff Planning', 'Planificacion de personal IA', 'text', 'partner_dashboard'),
  ('staff_title', 'AI Staff Planning', 'Planificacion de personal IA', 'text', 'partner_dashboard'),
  ('staff_expected_guests', 'Expected guests today', 'Clientes esperados hoy', 'text', 'partner_dashboard'),
  ('staff_recommended_servers', 'Recommended servers', 'Meseros recomendados', 'text', 'partner_dashboard'),
  ('staff_host_coverage', 'Recommended host coverage', 'Cobertura de host recomendada', 'text', 'partner_dashboard'),
  ('staff_peak_window', 'Peak window', 'Ventana pico', 'text', 'partner_dashboard'),
  ('staff_risk', 'Staffing risk', 'Riesgo de personal', 'text', 'partner_dashboard'),
  ('risk_low', 'Low', 'Bajo', 'text', 'partner_dashboard'),
  ('event_prediction_kicker', 'Nearby Event Prediction', 'Prediccion de eventos cercanos', 'text', 'partner_dashboard'),
  ('event_prediction_title', 'Nearby Event Prediction', 'Prediccion de eventos cercanos', 'text', 'partner_dashboard'),
  ('event_local_impact', 'Local event impact', 'Impacto de evento local', 'text', 'partner_dashboard'),
  ('event_traffic_lift', 'Expected traffic lift', 'Incremento esperado de trafico', 'text', 'partner_dashboard'),
  ('event_best_window', 'Best booking window', 'Mejor ventana de reserva', 'text', 'partner_dashboard'),
  ('ltv_kicker', 'Guest Lifetime Value Intelligence', 'Inteligencia de valor de vida del cliente', 'text', 'partner_dashboard'),
  ('ltv_title', 'Guest Lifetime Value Intelligence', 'Inteligencia de valor de vida del cliente', 'text', 'partner_dashboard'),
  ('ltv_average_guest_value', 'Average guest value', 'Valor medio de cliente', 'text', 'partner_dashboard'),
  ('ltv_returning_rate', 'Returning guest rate', 'Tasa de clientes recurrentes', 'text', 'partner_dashboard'),
  ('ltv_favorite_opportunity', 'Favorite guest opportunity', 'Oportunidad de clientes favoritos', 'text', 'partner_dashboard'),
  ('ltv_vip_potential', 'VIP potential guests', 'Clientes potenciales VIP', 'text', 'partner_dashboard'),
  ('vip_kicker', 'AI VIP Detection', 'Deteccion VIP IA', 'text', 'partner_dashboard'),
  ('vip_title', 'AI VIP Detection', 'Deteccion VIP IA', 'text', 'partner_dashboard'),
  ('vip_potential_week', 'Potential VIP guests this week', 'Clientes VIP potenciales esta semana', 'text', 'partner_dashboard'),
  ('vip_high_value_repeat', 'High-value repeat guests', 'Clientes recurrentes de alto valor', 'text', 'partner_dashboard'),
  ('vip_suggested_action', 'Send personalized offer', 'Enviar oferta personalizada', 'text', 'partner_dashboard'),
  ('marketing_kicker', 'AI Marketing Generator', 'Generador de marketing IA', 'text', 'partner_dashboard'),
  ('marketing_title', 'AI Marketing Generator', 'Generador de marketing IA', 'text', 'partner_dashboard'),
  ('marketing_generate', 'Generate message', 'Generar mensaje', 'text', 'partner_dashboard'),
  ('marketing_send_favorites', 'Send to favorites', 'Enviar a favoritos', 'text', 'partner_dashboard'),
  ('marketing_copy', 'Copy message', 'Copiar mensaje', 'text', 'partner_dashboard'),
  ('marketing_generated_notice', 'AI marketing message generated.', 'Mensaje de marketing IA generado.', 'text', 'partner_dashboard'),
  ('marketing_copied_notice', 'Marketing message copied.', 'Mensaje de marketing copiado.', 'text', 'partner_dashboard'),
  ('marketing_sent_notice', 'Marketing message prepared for favorite guests.', 'Mensaje de marketing preparado para clientes favoritos.', 'text', 'partner_dashboard'),
  ('social_post_created_notice', 'AI social post created for review.', 'Publicacion social IA creada para revisar.', 'text', 'partner_dashboard'),
  ('email_campaign_ready_notice', 'Email campaign prepared for favorite guests.', 'Campana de email preparada para clientes favoritos.', 'text', 'partner_dashboard')
on conflict (key) do update set
  value_en = excluded.value_en,
  value_es = excluded.value_es,
  content_type = excluded.content_type,
  group_name = excluded.group_name,
  updated_at = now();
