insert into site_content (key, value_en, value_es, content_type, group_name)
values
  ('seo_title', 'SmartTable AI | The AI Revenue Operating System for Restaurants', 'SmartTable AI | El sistema operativo de ingresos con IA para restaurantes', 'text', 'seo'),
  ('seo_meta_description', 'SmartTable AI combines reservations, guest personalization, predictive demand intelligence, and revenue recovery tools for New York restaurants.', 'SmartTable AI combina reservas, personalizacion para clientes, inteligencia predictiva de demanda y recuperacion de ingresos para restaurantes de Nueva York.', 'textarea', 'seo'),
  ('brand_title', 'SmartTable AI', 'SmartTable AI', 'text', 'site'),
  ('brand_subtitle', 'The AI Revenue Operating System for Restaurants', 'El sistema operativo de ingresos con IA para restaurantes', 'text', 'site'),
  ('hero_kicker', 'SmartTable AI', 'SmartTable AI', 'text', 'home'),
  ('hero_title', 'The AI Revenue Operating System for Restaurants', 'El sistema operativo de ingresos con IA para restaurantes', 'text', 'home'),
  ('hero_subtitle', 'Personalized dining for guests, predictive demand intelligence for restaurants, and smarter revenue recovery across New York.', 'Experiencias personalizadas para clientes, inteligencia predictiva de demanda para restaurantes y recuperacion inteligente de ingresos en Nueva York.', 'textarea', 'home'),
  ('top_actions_title', 'Top 3 Recommended Actions', 'Las 3 acciones recomendadas principales', 'text', 'partner_dashboard'),
  ('partner_nav_competitor', 'Competitors', 'Competidores', 'text', 'partner_dashboard'),
  ('partner_nav_menu_engineering', 'Menu', 'Menu', 'text', 'partner_dashboard'),
  ('partner_nav_dynamic_pricing', 'Dynamic pricing', 'Precios dinamicos', 'text', 'partner_dashboard'),
  ('partner_nav_loyalty_engine', 'Loyalty', 'Fidelizacion', 'text', 'partner_dashboard'),
  ('partner_nav_review_analyzer', 'Reviews', 'Resenas', 'text', 'partner_dashboard'),
  ('partner_nav_reputation', 'Reputation', 'Reputacion', 'text', 'partner_dashboard'),
  ('competitor_kicker', 'AI Competitor Tracker', 'Rastreador de competidores IA', 'text', 'partner_dashboard'),
  ('competitor_title', 'AI Competitor Tracker', 'Rastreador de competidores IA', 'text', 'partner_dashboard'),
  ('competitor_nearby_active', 'Nearby competitors active', 'Competidores cercanos activos', 'text', 'partner_dashboard'),
  ('competitor_avg_discount', 'Average local discount', 'Descuento local promedio', 'text', 'partner_dashboard'),
  ('competitor_your_discount', 'Your suggested discount', 'Tu descuento sugerido', 'text', 'partner_dashboard'),
  ('competitor_position', 'Competitive position', 'Posicion competitiva', 'text', 'partner_dashboard'),
  ('competitor_position_strong', 'Strong', 'Fuerte', 'text', 'partner_dashboard'),
  ('competitor_trend_label', 'Local competition trend', 'Tendencia competitiva local', 'text', 'partner_dashboard'),
  ('menu_engineering_kicker', 'AI Menu Engineering', 'Ingenieria de menu IA', 'text', 'partner_dashboard'),
  ('menu_engineering_title', 'AI Menu Engineering', 'Ingenieria de menu IA', 'text', 'partner_dashboard'),
  ('menu_best_margin', 'Best margin item', 'Producto con mejor margen', 'text', 'partner_dashboard'),
  ('menu_best_conversion', 'Best conversion item', 'Producto con mejor conversion', 'text', 'partner_dashboard'),
  ('menu_weak_item', 'Weak item', 'Producto debil', 'text', 'partner_dashboard'),
  ('menu_suggested_action', 'Promote high-margin items during weak demand windows.', 'Promociona productos de alto margen durante ventanas de baja demanda.', 'textarea', 'partner_dashboard'),
  ('dynamic_pricing_kicker', 'AI Dynamic Pricing', 'Precios dinamicos IA', 'text', 'partner_dashboard'),
  ('dynamic_pricing_title', 'AI Dynamic Pricing', 'Precios dinamicos IA', 'text', 'partner_dashboard'),
  ('pricing_window_label', 'Window', 'Ventana', 'text', 'partner_dashboard'),
  ('pricing_discount_label', 'Discount', 'Descuento', 'text', 'partner_dashboard'),
  ('pricing_demand_label', 'Demand', 'Demanda', 'text', 'partner_dashboard'),
  ('loyalty_engine_kicker', 'AI Loyalty Engine', 'Motor de fidelizacion IA', 'text', 'partner_dashboard'),
  ('loyalty_engine_title', 'AI Loyalty Engine', 'Motor de fidelizacion IA', 'text', 'partner_dashboard'),
  ('loyalty_favorite_guests', 'Favorite guests', 'Clientes favoritos', 'text', 'partner_dashboard'),
  ('loyalty_ready_to_return', 'Guests ready to return', 'Clientes listos para volver', 'text', 'partner_dashboard'),
  ('loyalty_recommended_campaign', 'Recommended campaign', 'Campana recomendada', 'text', 'partner_dashboard'),
  ('loyalty_campaign_example', 'Come back this week and enjoy 15% off.', 'Vuelve esta semana y disfruta 15% de descuento.', 'textarea', 'partner_dashboard'),
  ('loyalty_return_readiness', 'Return readiness', 'Preparacion para volver', 'text', 'partner_dashboard'),
  ('review_analyzer_kicker', 'AI Review Analyzer', 'Analizador de resenas IA', 'text', 'partner_dashboard'),
  ('review_analyzer_title', 'AI Review Analyzer', 'Analizador de resenas IA', 'text', 'partner_dashboard'),
  ('review_food_rating', 'Food rating', 'Calificacion de comida', 'text', 'partner_dashboard'),
  ('review_service_rating', 'Service rating', 'Calificacion de servicio', 'text', 'partner_dashboard'),
  ('review_ambience_rating', 'Ambience rating', 'Calificacion de ambiente', 'text', 'partner_dashboard'),
  ('review_sentiment_positive', 'Positive', 'Positivo', 'text', 'partner_dashboard'),
  ('review_sentiment_trend', 'Sentiment trend', 'Tendencia de sentimiento', 'text', 'partner_dashboard'),
  ('review_improvement_area', 'Main improvement area', 'Area principal de mejora', 'text', 'partner_dashboard'),
  ('reputation_kicker', 'AI Reputation Monitor', 'Monitor de reputacion IA', 'text', 'partner_dashboard'),
  ('reputation_title', 'AI Reputation Monitor', 'Monitor de reputacion IA', 'text', 'partner_dashboard'),
  ('reputation_score_label', 'Reputation', 'Reputacion', 'text', 'partner_dashboard'),
  ('reputation_overall_rating', 'Overall rating', 'Calificacion general', 'text', 'partner_dashboard'),
  ('reputation_rating_trend', 'Rating trend', 'Tendencia de calificacion', 'text', 'partner_dashboard'),
  ('reputation_negative_risk', 'Negative review risk', 'Riesgo de resena negativa', 'text', 'partner_dashboard'),
  ('reputation_satisfaction', 'Guest satisfaction', 'Satisfaccion de clientes', 'text', 'partner_dashboard')
on conflict (key) do update set
  value_en = excluded.value_en,
  value_es = excluded.value_es,
  content_type = excluded.content_type,
  group_name = excluded.group_name,
  updated_at = now();
