insert into public.site_content (key, value_en, value_es, content_type, group_name)
values
  ('partner_nav_weekly_intelligence', 'Weekly Intelligence', 'Inteligencia semanal', 'text', 'partner_dashboard'),
  ('partner_nav_advanced_ai', 'Advanced AI', 'IA avanzada', 'text', 'partner_dashboard'),
  ('partner_nav_guests', 'Guests', 'Clientes', 'text', 'partner_dashboard'),
  ('partner_nav_settings', 'Settings', 'Configuracion', 'text', 'partner_dashboard'),
  ('owner_today_ceo_kicker', 'AI CEO Dashboard', 'Panel CEO de IA', 'text', 'partner_dashboard'),
  ('owner_today_ceo_title', 'Today''s AI CEO Summary', 'Resumen CEO de IA de hoy', 'text', 'partner_dashboard'),
  ('owner_today_ceo_message', 'Good morning, {{restaurant_name}}. Friday 5:30-7:00 PM has weak demand. Rain may reduce demand by 18%. Recommended action: create a 15% early dinner offer and notify favorite guests. Expected gain today: +{{expected_gain}}. AI confidence: {{confidence}}%.', 'Buenos dias, {{restaurant_name}}. El viernes de 5:30 a 7:00 PM tiene demanda debil. La lluvia puede reducir la demanda en 18%. Accion recomendada: crear una oferta de cena temprana del 15% y avisar a clientes favoritos. Ganancia esperada hoy: +{{expected_gain}}. Confianza de IA: {{confidence}}%.', 'textarea', 'partner_dashboard'),
  ('owner_apply_ai_recommendation', 'Apply AI Recommendation', 'Aplicar recomendacion de IA', 'text', 'partner_dashboard'),
  ('owner_see_why', 'See why', 'Ver por que', 'text', 'partner_dashboard'),
  ('owner_edit_before_applying', 'Edit before applying', 'Editar antes de aplicar', 'text', 'partner_dashboard'),
  ('owner_main_risk', 'Main risk', 'Riesgo principal', 'text', 'partner_dashboard'),
  ('owner_main_opportunity', 'Main opportunity', 'Oportunidad principal', 'text', 'partner_dashboard'),
  ('owner_today_risk_copy', 'Rain may reduce demand by 18% around 6 PM.', 'La lluvia puede reducir la demanda en 18% cerca de las 6 PM.', 'textarea', 'partner_dashboard'),
  ('owner_today_opportunity_copy', 'Friday 5:30-7:00 PM has weak demand and recoverable tables.', 'El viernes de 5:30 a 7:00 PM tiene demanda debil y mesas recuperables.', 'textarea', 'partner_dashboard'),
  ('owner_today_recommendation_copy', 'Create a 15% early dinner offer and notify favorite guests.', 'Crear una oferta de cena temprana del 15% y avisar a clientes favoritos.', 'textarea', 'partner_dashboard'),
  ('owner_what_happened', 'What happened', 'Que paso', 'text', 'partner_dashboard'),
  ('owner_smarttable_recommends', 'What SmartTable recommends', 'Lo que recomienda SmartTable', 'text', 'partner_dashboard'),
  ('owner_expected_result', 'Expected result', 'Resultado esperado', 'text', 'partner_dashboard'),
  ('owner_expected_gain_copy', 'Recover approximately {{expected_gain}} today.', 'Recuperar aproximadamente {{expected_gain}} hoy.', 'text', 'partner_dashboard'),
  ('owner_recommended_action_kicker', 'Recommended AI action', 'Accion recomendada de IA', 'text', 'partner_dashboard'),
  ('owner_recommended_action_title', 'The one thing to do now', 'Lo principal para hacer ahora', 'text', 'partner_dashboard'),
  ('owner_notify_copy', 'Notify favorite and VIP guests after the offer is activated.', 'Avisar a clientes favoritos y VIP despues de activar la oferta.', 'textarea', 'partner_dashboard'),
  ('owner_confidence_simple', 'Strong enough for an owner decision, with deeper details below.', 'Suficiente para una decision del propietario, con mas detalles abajo.', 'textarea', 'partner_dashboard'),
  ('owner_recommendation_reason_margin', 'Discount stays inside restaurant margin guardrails.', 'El descuento se mantiene dentro de los limites de margen del restaurante.', 'text', 'partner_dashboard'),
  ('owner_value_month_title', 'SmartTable value this month', 'Valor de SmartTable este mes', 'text', 'partner_dashboard'),
  ('weekly_level_title', 'Plan the week without crowding today', 'Planifica la semana sin saturar el dia', 'text', 'partner_dashboard'),
  ('weekly_level_intro', 'Pricing, competitors, marketing, reviews, staffing, and the demand calendar live here for weekly planning.', 'Precios, competidores, marketing, resenas, personal y calendario de demanda viven aqui para planificacion semanal.', 'textarea', 'partner_dashboard'),
  ('advanced_level_title', 'Advanced operating intelligence', 'Inteligencia operativa avanzada', 'text', 'partner_dashboard'),
  ('advanced_level_intro', 'Deep AI modules are still available, but they no longer compete with the daily decision.', 'Los modulos avanzados de IA siguen disponibles, pero ya no compiten con la decision diaria.', 'textarea', 'partner_dashboard'),
  ('guests_level_title', 'Guest loyalty and return demand', 'Lealtad y retorno de clientes', 'text', 'partner_dashboard'),
  ('guests_level_intro', 'Use this when you want to grow repeat visits, favorites, and high-intent guest campaigns.', 'Usalo cuando quieras crecer visitas repetidas, favoritos y campanas de alta intencion.', 'textarea', 'partner_dashboard'),
  ('reviews_level_title', 'Reviews and post-visit intelligence', 'Resenas e inteligencia post-visita', 'text', 'partner_dashboard'),
  ('reviews_level_intro', 'Aggregated guest feedback, photo rewards, and review signals stay here.', 'Comentarios agregados, recompensas de fotos y senales de resenas estan aqui.', 'textarea', 'partner_dashboard'),
  ('edit_recommendation_notice', 'Recommendation opened for editing. Adjust discount, time window, or audience before applying.', 'Recomendacion abierta para editar. Ajusta descuento, horario o audiencia antes de aplicar.', 'textarea', 'partner_dashboard')
on conflict (key) do update
set value_en = excluded.value_en,
    value_es = excluded.value_es,
    content_type = excluded.content_type,
    group_name = excluded.group_name,
    updated_at = now();
